### ISSUE TITLE
submodules/jansson can't be found

### ISSUE THREAD

**Issue by leucinedreams** [signatumd/gpuminer-source#2]
I'm on an Ubuntu 16.04 system, and while jansson4 has been installed, compilation returns an error:

`submodules/Makefile.am:2: error: required directory submodules/jansson does not exist.`

I'm running installation as indicated in the README.md:

`git submodule init`
`git submodule update`
`autoreconf -i`

**Comment by andrew-kha** [comment]
Try this:
go to the submodules directory
git clone https://github.com/akheron/jansson

**Comment by leucinedreams** [comment]
This worked.
